<?php
/**
 * @category    Phagento
 * @package  Customerproducts
 * @copyright   Copyright (c) 2018
 * @author  Joenas Ejes <joenasejes@gmail.com>
 */
?>
<div class="view-mode">
    <?php $_modes = $this->getModes(); ?>
    <?php if ($_modes && count($_modes) > 1): ?>
        <label><?php echo $this->__('View as:') ?></label>
        <?php foreach ($this->getModes() as $_code => $_label): ?>
            <?php if ($this->isModeActive($_code)): ?>
                <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>
            <?php else: ?>
                <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>